# Generated by Django 3.2.6 on 2021-08-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210817_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userdetails',
            new_name='user_details',
        ),
    ]
