# Generated by Django 3.2.6 on 2021-08-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210818_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='MyappStudent',
        ),
        migrations.AlterModelTable(
            name='myappstudent',
            table='myapp_student',
        ),
    ]
